# docker-compose.yml (Final Version for Local Development)

services:
  # --- Django Application Service ("web") ---
  web:
    build:
      context: .
      dockerfile: Dockerfile # Explicitly use the main Dockerfile for local dev
    container_name: django_web_app
    command: gunicorn ai4s_online_test.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app # Mount local code for instant changes
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  # --- PostgreSQL Database Service ("db") ---
  db:
    image: postgres:15
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # This now uses the official environment variable names for the postgres image
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

  # --- Nginx Web Server Service ("nginx") ---
  nginx:
    image: nginx:1.25
    container_name: nginx_web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

# Define the named volumes to persist data.
volumes:
  postgres_data:
  static_volume:
  media_volume: