# docker-compose.yml (For Local Development ONLY)

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Use the main Dockerfile for local dev
    container_name: django_web_app
    # The command to run in development. Gunicorn will listen on port 8000.
    command: gunicorn ai4s_online_test.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app # Mount local code for instant changes
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ai4s_db
      - POSTGRES_USER=ai4s_user
      - POSTGRES_PASSWORD=a_strong_password_for_db
    env_file:
      - ./.env.dev

  nginx:
    image: nginx:1.25
    container_name: nginx_web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: