# Generated by Django 5.2.4 on 2025-08-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text="Tests are 'Draft' by default. They become 'Published' after reaching 15 questions.", max_length=20),
        ),
    ]
