# Generated by Django 5.2.4 on 2025-08-01 09:01

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Image will be resized to 600x400 pixels.', null=True, upload_to='test_images/originals/'),
        ),
    ]
